name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18
    
    - run: mkdir ./build

    - name: Build (linux/amd64)
      run: CGO_ENABLED=0 GOARCH=amd64 go build -v ./build/scraper

    - name: Build (windows/amd64)
      run: CGO_ENABLED=0 GOOS=windows GOARCH=amd64 go build -v ./build/scraper.exe
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v3.1.0
      with:
        name: build
        path: ./build
